CXXFLAGS=-Wall -Wextra -pedantic -ggdb -std=c++0x
BINDIR=../bin
BINS=exactot pexactot generador_grafo golosot

.PHONY: all clean

all: $(BINS)
	mv $(BINS) $(BINDIR)

clean:
	rm $(BINDIR)/exactot
	rm $(BINDIR)/pexactot
	rm $(BINDIR)/generador_grafo
	rm $(BINDIR)/golosot
	 
